### ISSUE TITLE
VPC subnetwork name

### ISSUE THREAD

**Issue by glavk** [terraform-yc-modules/terraform-yc-vpc#16]
Error message occurred in console after creating VPC subnet:

<img width="976" alt="terraform-yc-vpc" src="https://github.com/terraform-yc-modules/terraform-yc-vpc/assets/2370759/69b77f6d-eeeb-4853-85e4-7dad775b2b87">

**Comment by romati88** [comment]
Hi, tks! Plan to fix name check in API and name generation in module.
